---
- hosts: servers
  become: yes
  tasks:
    - name: Actualizar cache de software de apt
      apt:
        update_cache: yes

    - name: Instalar Apache
      apt:
        name: apache2
        state: present

    - name: Instalar cowsay
      apt:
        name: cowsay
        state: present

    - name: Crear un archivo
      copy:
        dest: /home/vagrant/archivo.txt
        content: "Contenido del archivo."

    - name: Copiar archivos
      copy:
        src: /path/to/local/file
        dest: /home/vagrant/

    - name: Crear carpetas
      file:
        path: /home/vagrant/nueva_carpeta
        state: directory

    - name: Iniciar servicio Apache
      service:
        name: apache2
        state: started

    - name: Agregar un usuario
      user:
        name: nuevo_usuario
        state: present

    - name: Ejecutar un script
      script: /path/to/local/script.sh
